# Generated by Django 5.2.4 on 2025-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('ру', 'Python'), ('html', 'HTML'), ('cpp', 'C++'), ('go', 'Golang'), ('js', 'JavaScript')], max_length=30),
        ),
    ]
