# Generated by Django 5.2.4 on 2025-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_user_alter_snippet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('js', 'JavaScript'), ('go', 'Golang'), ('html', 'HTML'), ('cpp', 'C++'), ('ру', 'Python')], max_length=30),
        ),
    ]
