# Generated by Django 5.2.4 on 2025-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_snippet_lang_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['name', 'lang']},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('cpp', 'C++'), ('go', 'Golang'), ('ру', 'Python'), ('html', 'HTML'), ('js', 'JavaScript')], max_length=30, verbose_name='Язык'),
        ),
    ]
